Vagrant.configure("2") do |config|

  config.vm.hostname = "lamp"

  # Our packaged basebox should be based of Ubuntu 12.04 32bit.

  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  # Forward HTTP requests.

  config.vm.network :forwarded_port, guest: 80, host: 8080

  # Provision the box with a shell script.
  
  config.vm.provision :shell, :path => "provision/provision.sh"

end