Vagrant::Config.run do |config|

  config.vm.host_name = "lamp-dev"

  # Our packaged basebox should be based of Ubuntu 12.10 64bit.

  config.vm.box = "quantal64"
  config.vm.box_url = "https://github.com/downloads/roderik/VagrantQuantal64Box/quantal64.box"

  # Initialize host-only networking.

  config.vm.network :hostonly, "10.0.1.10"

  # Forward HTTP requests.

  config.vm.forward_port 80, 8080

  # Provision the box with a shell script.

  Vagrant::Config.run do |config|
    config.vm.provision :shell, :path => "provision/provision.sh"
  end

end